// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.3
// source: testp/testp.proto

package test_quadro

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Book struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Author *Author `protobuf:"bytes,2,req,name=author" json:"author,omitempty"`
}

func (x *Book) Reset() {
	*x = Book{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testp_testp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_testp_testp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_testp_testp_proto_rawDescGZIP(), []int{0}
}

func (x *Book) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Book) GetAuthor() *Author {
	if x != nil {
		return x.Author
	}
	return nil
}

type Author struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
}

func (x *Author) Reset() {
	*x = Author{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testp_testp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Author) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Author) ProtoMessage() {}

func (x *Author) ProtoReflect() protoreflect.Message {
	mi := &file_testp_testp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Author.ProtoReflect.Descriptor instead.
func (*Author) Descriptor() ([]byte, []int) {
	return file_testp_testp_proto_rawDescGZIP(), []int{1}
}

func (x *Author) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

var File_testp_testp_proto protoreflect.FileDescriptor

var file_testp_testp_proto_rawDesc = []byte{
	0x0a, 0x11, 0x74, 0x65, 0x73, 0x74, 0x70, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x74, 0x65, 0x73, 0x74, 0x70, 0x22, 0x41, 0x0a, 0x04, 0x42, 0x6f,
	0x6f, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x25, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x18, 0x02, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x70, 0x2e, 0x41,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x22, 0x1c, 0x0a,
	0x06, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0x5f, 0x0a, 0x09, 0x42,
	0x6f, 0x6f, 0x6b, 0x53, 0x68, 0x65, 0x6c, 0x66, 0x12, 0x27, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x42,
	0x6f, 0x6f, 0x6b, 0x12, 0x0d, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x70, 0x2e, 0x41, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x1a, 0x0b, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x70, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x22,
	0x00, 0x12, 0x29, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x0b,
	0x2e, 0x74, 0x65, 0x73, 0x74, 0x70, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x1a, 0x0d, 0x2e, 0x74, 0x65,
	0x73, 0x74, 0x70, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x22, 0x00, 0x42, 0x15, 0x5a, 0x13,
	0x67, 0x6f, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x71, 0x75, 0x61, 0x64,
	0x72, 0x6f, 0x2f,
}

var (
	file_testp_testp_proto_rawDescOnce sync.Once
	file_testp_testp_proto_rawDescData = file_testp_testp_proto_rawDesc
)

func file_testp_testp_proto_rawDescGZIP() []byte {
	file_testp_testp_proto_rawDescOnce.Do(func() {
		file_testp_testp_proto_rawDescData = protoimpl.X.CompressGZIP(file_testp_testp_proto_rawDescData)
	})
	return file_testp_testp_proto_rawDescData
}

var file_testp_testp_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_testp_testp_proto_goTypes = []interface{}{
	(*Book)(nil),   // 0: testp.Book
	(*Author)(nil), // 1: testp.Author
}
var file_testp_testp_proto_depIdxs = []int32{
	1, // 0: testp.Book.author:type_name -> testp.Author
	1, // 1: testp.BookShelf.GetBook:input_type -> testp.Author
	0, // 2: testp.BookShelf.GetAuthor:input_type -> testp.Book
	0, // 3: testp.BookShelf.GetBook:output_type -> testp.Book
	1, // 4: testp.BookShelf.GetAuthor:output_type -> testp.Author
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_testp_testp_proto_init() }
func file_testp_testp_proto_init() {
	if File_testp_testp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_testp_testp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Book); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testp_testp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Author); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_testp_testp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_testp_testp_proto_goTypes,
		DependencyIndexes: file_testp_testp_proto_depIdxs,
		MessageInfos:      file_testp_testp_proto_msgTypes,
	}.Build()
	File_testp_testp_proto = out.File
	file_testp_testp_proto_rawDesc = nil
	file_testp_testp_proto_goTypes = nil
	file_testp_testp_proto_depIdxs = nil
}
